server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://grocery-api.cvtq9j4axrge.us-east-1.rds.amazonaws.com:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger